// Code generated by prana; DO NOT EDIT.

// Package database_tests contains a tests for database repository
// Auto-generated at Fri, 12 Apr 2019 13:09:45 CEST

package database_test

import (
	"os"
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"

	"github.com/phogolabs/orm"
	"github.com/phogolabs/parcello"
)

var (
	gateway *orm.Gateway
)

func TestDatabase(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Database Suite")
}

var _ = BeforeSuite(func() {
	var (
		err error
		url = os.Getenv("TEST_DB_URL")
	)

	if url == "" {
		Skip("TEST_DB_URL environment variable is not set")
		return
	}

	gateway, err = orm.Connect(url)
	Expect(err).NotTo(HaveOccurred())

	Expect(gateway).NotTo(BeNil())
	Expect(gateway.Migrate(parcello.ManagerAt("migration"))).To(Succeed())
	Expect(gateway.ReadDir(parcello.ManagerAt("routine"))).To(Succeed())
})

var _ = AfterSuite(func() {
	if gateway == nil {
		return
	}

	Expect(gateway.Close()).To(Succeed())
})
