// Code generated by prana; DO NOT EDIT.

// Package model contains an object model of database schema 'default'
// Auto-generated at Tue, 02 Apr 2019 10:49:28 CEST

package model

import "github.com/phogolabs/schema"

// User represents a data base table 'users'
type User struct {
	// ID represents a database column 'id' of type 'INT PRIMARY KEY NOT NULL'
	ID int `db:"id,primary_key,not_null" validate:"required"`
	// FirstName represents a database column 'first_name' of type 'TEXT NOT NULL'
	FirstName string `db:"first_name,not_null" validate:"required,gt=0"`
	// LastName represents a database column 'last_name' of type 'TEXT NULL'
	LastName schema.NullString `db:"last_name,null" validate:"-"`
}
