// Code generated by prana; DO NOT EDIT.

// Package model contains an object model of database schema 'default'
// Auto-generated at Thu, 11 Apr 2019 16:39:45 CEST

package ent

// User represents a data base table 'users'
type User struct {
	// ID represents a database column 'id' of type 'INT PRIMARY KEY NOT NULL'
	ID int `db:"id,primary_key,not_null" validate:"required" json:"id"`
	// FirstName represents a database column 'first_name' of type 'TEXT NOT NULL'
	FirstName string `db:"first_name,not_null" validate:"required,gt=0" json:"first_name"`
	// LastName represents a database column 'last_name' of type 'TEXT NULL'
	LastName *string `db:"last_name,null" validate:"-" json:"last_name"`
}
